version: '3.8'

services:
  postgresdb:
    image: postgres:15-alpine
    container_name: trade-postgres
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trade-network

  app:
    depends_on:
      - postgresdb
    build: 
      context: ./trade-app
      dockerfile: Dockerfile
    container_name: trade-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${POSTGRESDB_USER}
      - DB_PASSWORD=${POSTGRESDB_ROOT_PASSWORD}
      - DB_NAME=${POSTGRESDB_DATABASE}
      - DB_PORT=${POSTGRESDB_DOCKER_PORT}
      - NODE_DOCKER_PORT=${NODE_DOCKER_PORT}
    stdin_open: true
    tty: true
    networks:
      - trade-network

volumes:
  postgres_data:

networks:
  trade-network:
    driver: bridge